version: "3.9"


services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/fakebank_testdata
    environment:
      - POSTGRES_PASSWORD=fakebank
      - POSTGRES_USER=fakebank
      - POSTGRES_DB=test
