"""add_created_and_status_cols_to_transaction_model

Revision ID: 0b55c3cc0f04
Revises: 631b12cc6419
Create Date: 2024-02-17 00:05:07.217123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b55c3cc0f04'
down_revision: Union[str, None] = '631b12cc6419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'status')
    op.drop_column('transaction', 'created_at')
    # ### end Alembic commands ###
