"""add_transaction_model

Revision ID: 631b12cc6419
Revises: aa33233d2848
Create Date: 2024-02-16 23:52:05.754542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631b12cc6419'
down_revision: Union[str, None] = 'aa33233d2848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transaction',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('sent_from', sa.UUID(), nullable=False),
        sa.Column('sent_to', sa.UUID(), nullable=False),
        sa.Column('amount', sa.DECIMAL(), nullable=False),
        sa.CheckConstraint('amount > 0'),
        sa.CheckConstraint('sent_from != sent_to'),
        sa.ForeignKeyConstraint(['sent_from'], ['account.id'],),
        sa.ForeignKeyConstraint(['sent_to'], ['account.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
