"""add_account_and_trans_models

Revision ID: e98d0256b52f
Revises: c80f15e33999
Create Date: 2024-03-05 23:42:53.954897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98d0256b52f'
down_revision: Union[str, None] = 'c80f15e33999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('balance', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.UUID(), nullable=False),
    sa.Column('recipient', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.CheckConstraint('amount > 0'),
    sa.CheckConstraint('recipient != sender'),
    sa.ForeignKeyConstraint(['recipient'], ['account.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('account')
    # ### end Alembic commands ###
