basePath: /api/v1
definitions:
  users.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      is_superuser:
        type: boolean
      is_verified:
        type: boolean
      last_name:
        type: string
    type: object
  users.UserLoginData:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  users.UserPage:
    properties:
      data:
        items:
          $ref: '#/definitions/users.User'
        type: array
      total:
        type: integer
    type: object
  users.UserRegisterData:
    properties:
      email:
        type: string
      first_name:
        type: string
      is_active:
        type: boolean
      is_superuser:
        type: boolean
      is_verified:
        type: boolean
      last_name:
        type: string
      password:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: FakeBank API
  version: "1.0"
paths:
  /auth/signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Credentials
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/users.UserLoginData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Sign In
      tags:
      - users
      - auth
  /users/:
    get:
      consumes:
      - application/json
      description: List user
      parameters:
      - description: Offset
        in: query
        name: offset
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.UserPage'
      summary: List user
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: User Register Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.UserRegisterData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Create new user
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Retrieve user
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
